name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./my-app
          file: ./my-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.sha }}
          platforms: linux/amd64,linux/arm64  # 멀티 아키텍처 지원 추가

      - name: Update Kubernetes manifest and push to deploy branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          
          # Checkout deploy branch
          git fetch origin deploy
          git checkout deploy

          # Update manifests/deployment.yml with the new image tag
          sed -i "s|image: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:.*|image: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.sha }}|" manifests/deployment.yaml

          # Commit and push changes to deploy branch
          git add manifests/deployment.yml
          git commit -m "Update image to ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.sha }}"
          git push origin deploy

      - name: Log out from Docker Hub
        run: docker logout
